Update redirects in login sapling
Cargill/splinter-ui pull request #20
Opened 2020-05-01 21:52 UTC by RyanLassigBanks

Update how the login sapling redirects a user to the page they were
attempting to navigate to. This is to make it compatible with updates
being made to Canopyjs which will now redirect users to the login page
if they're not logged in. Canopyjs redirects will cause the history to
contain the page the user requested so login simply needs to return that
user to that page after they have been logged in.

Signed-off-by: Ryan Banks <rbanks@bitwise.io>

2020-05-05 20:41 UTC, dplumb94 requested changes
This appears to have fixed the bug where you can access a sapling before you are logged in which is great. I am seeing some strange functionality where I navigate to a page while not logged in (say /profile). I am redirected to the login sapling as expected and my path is updated to /login. However, once I do log in, I'm brought to the main page, but my path says /profile even though the profile sapling is not rendered. I tested this PR in tandem with the CanopyJS PR so the bug could be in either component.

Also, I wonder if there is any way to avoid the Canopy sidebar rendering at all before the user is logged in, instead of appearing to redirect/reload to the login page.

2020-05-06 22:24 UTC, RyanLassigBanks commented
>Also, I wonder if there is any way to avoid the Canopy sidebar rendering at all before the user is logged in, instead of appearing to redirect/reload to the login page.

Added commit removing call to hideCanopy from login sapling and updated canopy js commit to call hideCanopy before redirecting to login page

2020-05-06 22:28 UTC, RyanLassigBanks commented
>This appears to have fixed the bug where you can access a sapling before you are logged in which is great. I am seeing some strange functionality where I navigate to a page while not logged in (say /profile). I am redirected to the login sapling as expected and my path is updated to /login. However, once I do log in, I'm brought to the main page, but my path says /profile even though the profile sapling is not rendered. I tested this PR in tandem with the CanopyJS PR so the bug could be in either component.

I changed how the redirects were being handled to no longer use `history.goBack` as was the case in my previous commit, so I think I've managed to fix this.

2020-05-07 16:00 UTC, eloaverona reviewed
Tested and seems to work.  Just one comment.

2020-05-07 16:41 UTC, eloaverona commented on saplings/register-login/src/index.ts
> +interface Canopy {
Is this really necessary here? I think it makes more sense as part of the splinter ui app itself, where $CANOPY is initially defined in `splinter-ui/app/src/App.js`

2020-05-07 17:16 UTC, eloaverona approved these changes
Tested

2020-05-21 20:52 UTC, dplumb94 approved these changes

2020-05-21 20:52 UTC, merged