Add register-login and profile saplings from Grid
Cargill/splinter-ui pull request #4
Opened 2020-04-09 14:24 UTC by eloaverona

This PR adds the register-login and profiles saplings that are being developed as part of the Grid  UI work. 

### To test:
1. Run:
```
docker-compose -f docker/docker-compose.yaml up --build
```

2. Go to `http://localhost:3030/`. You will be asked to login as an existing user or register a new user:
<img width="1256" alt="Screen Shot 2020-04-09 at 9 20 45 AM" src="https://user-images.githubusercontent.com/14094978/78905339-76a2ce00-7a43-11ea-8af2-14d9935bcfe0.png">

3. Once you've register a new user, click the profile icon in the bottom left corner on the menu, which you forward you to `http://localhost:3030/profile`:
<img width="1256" alt="Screen Shot 2020-04-09 at 9 23 09 AM" src="https://user-images.githubusercontent.com/14094978/78905524-c2557780-7a43-11ea-885c-4f36c59bb272.png">

P.S The profile sapling is still under active development so bugs or issues might be present.

2020-04-09 16:36 UTC, agunde406 approved these changes
tested locally

2020-04-09 16:47 UTC, vaporos commented on sapling-dev-server/Dockerfile
> +RUN git clone https://github.com/hyperledger/grid
We should hack this in reverse, so that the official code is here and grid is dependent on splinter.

2020-04-09 19:56 UTC, dplumb94 requested changes
I am getting a 404 when trying to add a key in the Profile sapling: 
`splinter-ui-alpha           | 172.25.0.1 - - [09/Apr/2020:19:52:09 +0000] "POST /splinterd/biome/users/7e6b258b-1521-4145-a94a-1e53ddc479ea/keys HTTP/1.1" 404 -`

This may be due to the docker image env vars. You may need to name them according to the node since the SPLINTER_URL variables get built into the image

2020-04-10 12:58 UTC, eloaverona commented
@dplumb94 The issue you mentioned is in the profile sapling, and is being fixed in this PR https://github.com/hyperledger/grid/pull/224

2020-04-10 14:33 UTC, dplumb94 approved these changes

2020-04-10 14:36 UTC, merged