Convert build from react scripts to webpack
Cargill/splinter-ui pull request #45
Opened 2020-08-19 17:12 UTC by peterschwarz

Remove the use of react scripts from the profile sapling, and replace it with a similar configuration used in the circuits sapling.

The circuit sapling was converted in PR #38

2020-08-21 17:17 UTC, dplumb94 requested changes
getting an error building in docker: 
```> npm run generate-proto-files && webpack

npm ERR! missing script: generate-proto-files

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-21T17_16_02_071Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! profile@0.0.0-alpha build: `npm run generate-proto-files && webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the profile@0.0.0-alpha build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-21T17_16_02_104Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! profile@0.0.0-alpha deploy: `npm run build && npm run add-to-canopy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the profile@0.0.0-alpha deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-21T17_16_02_141Z-debug.log
ERROR: Service 'sapling-dev-server-alpha' failed to build: The command '/bin/sh -c cd /saplings/profile &&   npm install &&   npm run deploy' returned a non-zero code: 1```

2020-08-24 14:01 UTC, peterschwarz commented
Missed a line when copying the circuit sapling configuration. Fixed now.

2020-08-24 16:49 UTC, dplumb94 approved these changes

2020-09-23 17:19 UTC, vaporos approved these changes

2020-10-08 16:07 UTC, merged