Fix `display_name` and `user_id` regexes
Cargill/splinter-ui pull request #57
Opened 2020-11-11 20:46 UTC by shannynalayna

Fixes the regexes used to extract the `display_name` and the `user_id`
from the redirect URL used once authentication has completed.
Previously, the character used at the beginning of these regexes was a
`?`, where it should have been `&` to collect query parameters.

Signed-off-by: Shannyn Telander <telander@bitwise.io>

2020-11-11 20:49 UTC, ltseeley commented on saplings/oauth-login/src/index.js
> +    const userIdRegex = /&user_id=([^&#]*)|&|$/;
These regexes assume a particular order to the query parameters; they should probably allow for them to be in any order (each could be preceded by `?` or `&`).

2020-11-11 20:51 UTC, peterschwarz requested changes

2020-11-11 20:51 UTC, peterschwarz commented on saplings/oauth-login/src/index.js
> +    const userIdRegex = /&user_id=([^&#]*)|&|$/;
These should not be expected in a particular order. You could match on the class `[\?|&]`. This would be true for all three Paramus.

2020-11-12 17:11 UTC, ltseeley approved these changes

2020-11-12 21:19 UTC, peterschwarz approved these changes

2020-11-12 21:24 UTC, merged