Update many dependencies
Cargill/splinter-ui pull request #85
Opened 2021-04-16 17:00 UTC by dnewh

This updates many dependencies that were reporting security
vulnerabilities.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2021-05-13 15:55 UTC, shannynalayna approved these changes, later dismissed

2021-05-13 16:13 UTC, isabeltomb approved these changes, later dismissed

2021-05-13 16:47 UTC, peterschwarz requested changes
Change the commit summary to:

"Update deps with reported security vulnerabilities"

The current summary is too vague

2021-05-13 16:48 UTC, peterschwarz commented on app/package.json
> +    "eslint": "^7.24.0",
Doesn't this need to be fixed at `7.22.0`, due to a bug in the linter?

2021-05-13 17:06 UTC, peterschwarz approved these changes, later dismissed

2021-05-13 17:48 UTC, isabeltomb approved these changes, later dismissed

2021-05-13 18:00 UTC, shannynalayna submitted a review, later dismissed

2021-05-14 17:19 UTC, isabeltomb approved these changes

2021-05-14 17:27 UTC, peterschwarz approved these changes

2021-05-14 17:32 UTC, shannynalayna approved these changes

2021-05-14 18:15 UTC, merged