Update circuit sapling styles
Cargill/splinter-ui pull request #96
Opened 2021-05-18 21:40 UTC by dnewh

This updates the circuit sapling styles so that the sapling displays
correctly in Grid. This does not update the sapling to match the Grid
design system. That work will need further discussion

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2021-05-25 19:47 UTC, Caleb-Hill submitted a review, later dismissed

2021-05-25 20:58 UTC, dplumb94 requested changes
Can you please expand on the rationale for each of the changes in the commit message? It is difficult to review/maintain this styling without context of why some of the attributes were updated. 

Something like "we had to change --color-light-grey to --color grey because... " for each of the changes would make this a lot easier to review and maintain later on.

2021-06-07 20:33 UTC, dplumb94 approved these changes

2021-06-07 20:43 UTC, shannynalayna approved these changes
Tested

2021-06-07 20:44 UTC, merged